# 服务相关配置
server:
  name: app-sample
  host: 127.0.0.1
  port: 15001
  mode: debug

# 数据库配置
db:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbName: sample
  create-table: true
  debug: true
  slowSql: 3s
  # 数据库连接池
  pool:
    maxOpenConn: 300  # 最大连接
    maxIdleConn: 10   # 最小空闲连接数
    maxLifeTime: 1h
