// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/redis/go-redis/v9"
	"go-sample/api"
	"go-sample/api/example"
	"go-sample/api/ping"
	"go-sample/internal/dao"
	"go-sample/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// 模块依赖注入，获取API路由列表
func initModules(db *gorm.DB, client *redis.Client) ([]api.Module, error) {
	exampleRepo := dao.NewExampleRepo(db)
	exampleService := service.NewExampleService(exampleRepo)
	exampleExample := example.NewExample(exampleService)
	pingRepo := dao.NewPingRepo(db)
	pingService := service.NewPingService(pingRepo, client)
	pingPing := ping.NewPing(pingService)
	v := ProvideModules(exampleExample, pingPing)
	return v, nil
}

// wire.go:

func ProvideModules(exam *example.Example, ping2 *ping.Ping) []api.Module {
	return []api.Module{
		exam, ping2,
	}
}
