// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/redis/go-redis/v9"
	"go-sample/api"
	"go-sample/api/email"
	"go-sample/api/example"
	"go-sample/api/ping"
	"go-sample/internal/service"
	"go-sample/internal/store"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// 模块依赖注入，获取API路由列表
func initModules(db *gorm.DB, client *redis.Client) ([]api.Module, error) {
	exampleStore := store.NewExampleStore(db)
	exampleService := service.NewExampleService(exampleStore)
	exampleExample := example.NewExample(exampleService)
	pingStore := store.NewPingStore(db)
	pingService := service.NewPingService(pingStore, client)
	pingPing := ping.NewPing(pingService)
	emailEmail := email.NewEmail()
	v := ProvideModules(exampleExample, pingPing, emailEmail)
	return v, nil
}

// wire.go:

func ProvideModules(exam *example.Example, ping2 *ping.Ping, email2 *email.Email) []api.Module {
	return []api.Module{
		exam, ping2, email2,
	}
}
